import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';
import { Pencil, Plus, ShieldCheck, Trash2 } from 'lucide-react';

export default function Index({ roles, canManage }) {
    const systemRoles = ['super_admin', 'admin', 'counsellor'];
    const remove = (role) => { if (confirm(`Delete the ${role.name} role?`)) router.delete(route('admin.roles.destroy', role.id)); };

    return <AdminLayout title="Roles & Permissions"><Head title="Roles & Permissions" /><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">Roles & permissions</h2><p className="mt-1 text-sm text-slate-500">Control access through reusable, server-enforced permission groups.</p></div>{canManage && <Link href={route('admin.roles.create')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> New role</Link>}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <article key={role.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="rounded-xl bg-teal-50 p-3 text-teal-700"><ShieldCheck className="h-5 w-5" /></span><div><h3 className="font-semibold capitalize">{role.name.replaceAll('_', ' ')}</h3><p className="text-xs text-slate-500">{role.users_count} users</p></div></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{role.permissions_count} permissions</span></div>{canManage && role.name !== 'super_admin' && <div className="mt-5 flex justify-end gap-2 border-t border-slate-100 pt-4"><Link href={route('admin.roles.edit', role.id)} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm text-teal-700 hover:bg-teal-50"><Pencil className="h-4 w-4" /> Edit</Link>{!systemRoles.includes(role.name) && role.users_count === 0 && <button onClick={() => remove(role)} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm text-rose-700 hover:bg-rose-50"><Trash2 className="h-4 w-4" /> Delete</button>}</div>}</article>)}</div></AdminLayout>;
}
