import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Link } from '@inertiajs/react';

export default function RoleForm({ form, permissionGroups, submitLabel }) {
    const toggle = (permission) => form.setData('permissions', form.data.permissions.includes(permission) ? form.data.permissions.filter((item) => item !== permission) : [...form.data.permissions, permission]);
    return <form onSubmit={form.submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><InputLabel value="Role name" /><TextInput value={form.data.name} onChange={(e) => form.setData('name', e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, '_'))} className="mt-1 block w-full" required /><p className="mt-1 text-xs text-slate-500">Use lowercase letters, numbers, and underscores.</p><InputError message={form.errors.name} className="mt-2" /></div><div><h3 className="font-semibold">Permissions</h3><p className="text-sm text-slate-500">A role needs an appropriate dashboard permission to sign in to a workspace.</p><InputError message={form.errors.permissions} className="mt-2" /><div className="mt-4 grid gap-4 lg:grid-cols-2">{Object.entries(permissionGroups).map(([group, permissions]) => <section key={group} className="rounded-xl border border-slate-200 p-4"><h4 className="mb-3 text-sm font-semibold text-slate-800">{group}</h4><div className="space-y-2">{permissions.map((permission) => <label key={permission} className="flex items-center gap-3 text-sm text-slate-600"><input type="checkbox" checked={form.data.permissions.includes(permission)} onChange={() => toggle(permission)} className="rounded border-slate-300 text-teal-600 focus:ring-teal-500" /><span>{permission}</span></label>)}</div></section>)}</div></div><div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><Link href={route('admin.roles.index')} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-600">Cancel</Link><PrimaryButton disabled={form.processing}>{submitLabel}</PrimaryButton></div></form>;
}
