<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $invoice->receipt_number }}</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #1e293b;
            font-size: 12px;
        }

        .header {
            border-bottom: 2px solid #059669;
            padding-bottom: 18px;
            margin-bottom: 24px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            margin: 0;
        }

        .paid {
            color: #047857;
            font-size: 16px;
            font-weight: bold;
        }

        .muted {
            color: #64748b;
        }

        .box {
            border: 1px solid #e2e8f0;
            padding: 16px;
            margin-top: 20px;
        }
    </style>
</head>

<body>
<div class="header">
    <p class="title">Susadhya Counselling</p>
    <p class="paid">PAYMENT RECEIPT</p>
</div>

<div class="box">
    <p>
        <strong>Receipt:</strong>
        {{ $invoice->receipt_number }}
    </p>

    <p>
        <strong>Invoice:</strong>
        {{ $invoice->invoice_number }}
    </p>

    <p>
        <strong>Client:</strong>
        {{ $invoice->billing_name }}
    </p>

    <p>
        <strong>Service:</strong>
        {{ $invoice->payment->appointment->counsellingService?->name ?? 'Counselling service' }}
    </p>

    <p>
        <strong>Paid:</strong>
        {{ $invoice->currency }}
        {{ number_format((float) $invoice->total, 2) }}
    </p>

    <p>
        <strong>Payment method:</strong>
        {{ ucfirst($invoice->payment->method) }}
    </p>

    <p>
        <strong>Reference:</strong>
        {{ $invoice->payment->provider_reference ?: 'Not provided' }}
    </p>

    <p>
        <strong>Paid at:</strong>
        {{ $invoice->paid_at?->format('Y-m-d H:i') }}
    </p>
</div>

<p class="muted" style="margin-top: 30px;">
    Generated by the Susadhya Counselling Platform.
</p>
</body>
</html>
