<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Susadhya Operational Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #1e293b;
        }

        h1,
        h2 {
            margin: 0 0 10px;
        }

        .meta {
            margin-bottom: 18px;
            color: #475569;
        }

        .summary {
            width: 100%;
            margin-bottom: 18px;
            border-collapse: collapse;
        }

        .summary td {
            width: 25%;
            padding: 8px;
            border: 1px solid #cbd5e1;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.data th,
        table.data td {
            border: 1px solid #cbd5e1;
            padding: 5px;
            vertical-align: top;
        }

        table.data th {
            background: #f1f5f9;
            text-align: left;
        }

        .section {
            margin-top: 22px;
        }

        .muted {
            color: #64748b;
        }
    </style>
</head>

<body>
    <h1>Susadhya Counselling</h1>
    <h2>Operational Report</h2>

    <div class="meta">
        Period:
        {{ $filters['from'] }}
        to
        {{ $filters['to'] }}
        <br>

        Generated:
        {{ $generatedAt->format('Y-m-d H:i') }}
        <br>

        Generated by:
        {{ $generatedBy }}
    </div>

    <table class="summary">
        <tr>
            <td>
                <strong>Total</strong><br>
                {{ $summary['total'] }}
            </td>

            <td>
                <strong>Completed</strong><br>
                {{ $summary['completed'] }}
            </td>

            <td>
                <strong>Cancelled</strong><br>
                {{ $summary['cancelled'] }}
            </td>

            <td>
                <strong>No Show</strong><br>
                {{ $summary['no_show'] }}
            </td>
        </tr>

        <tr>
            <td>
                <strong>Pending</strong><br>
                {{ $summary['pending'] }}
            </td>

            <td>
                <strong>Confirmed</strong><br>
                {{ $summary['confirmed'] }}
            </td>

            <td>
                <strong>Utilisation</strong><br>
                {{ number_format($summary['utilisation_rate'], 2) }}%
            </td>

            <td>
                <strong>Cancellation Rate</strong><br>
                {{ number_format($summary['cancellation_rate'], 2) }}%
            </td>
        </tr>
    </table>

    <div class="section">
        <h2>Counsellor Activity</h2>

        <table class="data">
            <thead>
                <tr>
                    <th>Counsellor</th>
                    <th>Total</th>
                    <th>Completed</th>
                    <th>No Show</th>
                    <th>Cancelled</th>
                    <th>Utilisation</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($counsellorActivity as $row)
                    <tr>
                        <td>{{ $row['name'] }}</td>
                        <td>{{ $row['total_appointments'] }}</td>
                        <td>{{ $row['completed_appointments'] }}</td>
                        <td>{{ $row['no_show_appointments'] }}</td>
                        <td>{{ $row['cancelled_appointments'] }}</td>
                        <td>
                            {{ number_format($row['utilisation_rate'], 2) }}%
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Cancellations by Service</h2>

        <table class="data">
            <thead>
                <tr>
                    <th>Service</th>
                    <th>Cancelled</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($cancellationsByService as $row)
                    <tr>
                        <td>{{ $row['service_name'] }}</td>
                        <td>{{ $row['cancellation_count'] }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2">
                            No cancellations in this period.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Appointments</h2>

        <table class="data">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Client</th>
                    <th>Counsellor</th>
                    <th>Service</th>
                    <th>Mode</th>
                    <th>Status</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($appointments as $appointment)
                    <tr>
                        <td>
                            {{ $appointment['appointment_date'] }}
                        </td>

                        <td>
                            {{ $appointment['start_time'] }}
                            -
                            {{ $appointment['end_time'] }}
                        </td>

                        <td>
                            {{ $appointment['client_name'] }}
                        </td>

                        <td>
                            {{ $appointment['counsellor_name'] }}
                        </td>

                        <td>
                            {{ $appointment['service_name'] }}
                        </td>

                        <td>
                            {{ str_replace('_', ' ', ucfirst($appointment['mode'])) }}
                        </td>

                        <td>
                            {{ str_replace('_', ' ', ucfirst($appointment['status'])) }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <p class="muted">
        Utilisation =
        completed / (completed + no-show) appointments.
        Clinical note content is excluded from this report.
    </p>
</body>
</html>
