<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Susadhya Revenue Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #1e293b;
        }

        h1,
        h2 {
            margin: 0 0 10px;
        }

        .meta {
            margin-bottom: 18px;
            color: #475569;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #cbd5e1;
            padding: 5px;
            vertical-align: top;
        }

        th {
            background: #f1f5f9;
            text-align: left;
        }

        .section {
            margin-top: 22px;
        }

        .right {
            text-align: right;
        }

        .muted {
            color: #64748b;
        }
    </style>
</head>

<body>
    <h1>Susadhya Counselling</h1>
    <h2>Revenue Report</h2>

    <div class="meta">
        Period:
        {{ $filters['from'] }}
        to
        {{ $filters['to'] }}
        <br>

        Generated:
        {{ $generatedAt->format('Y-m-d H:i') }}
        <br>

        Generated by:
        {{ $generatedBy }}
    </div>

    <div class="section">
        <h2>Revenue by Currency</h2>

        <table>
            <thead>
                <tr>
                    <th>Currency</th>
                    <th>Payments</th>
                    <th>Gross</th>
                    <th>Refunded</th>
                    <th>Net</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($summary['currency_totals'] as $row)
                    <tr>
                        <td>{{ $row['currency'] }}</td>

                        <td>
                            {{ $row['payment_count'] }}
                        </td>

                        <td class="right">
                            {{ number_format($row['gross_amount'], 2) }}
                        </td>

                        <td class="right">
                            {{ number_format($row['refunded_amount'], 2) }}
                        </td>

                        <td class="right">
                            {{ number_format($row['net_amount'], 2) }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Payment Method Breakdown</h2>

        <table>
            <thead>
                <tr>
                    <th>Method</th>
                    <th>Currency</th>
                    <th>Count</th>
                    <th>Total</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($summary['method_breakdown'] as $row)
                    <tr>
                        <td>{{ ucfirst($row['method']) }}</td>
                        <td>{{ $row['currency'] }}</td>
                        <td>{{ $row['payment_count'] }}</td>

                        <td class="right">
                            {{ number_format($row['total_amount'], 2) }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Payment Source Records</h2>

        <table>
            <thead>
                <tr>
                    <th>Paid At</th>
                    <th>Payment UUID</th>
                    <th>Appointment</th>
                    <th>Service</th>
                    <th>Method</th>
                    <th>Currency</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Reconciliation</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($payments as $payment)
                    <tr>
                        <td>{{ $payment['paid_at'] }}</td>
                        <td>{{ $payment['uuid'] }}</td>

                        <td>
                            {{ $payment['appointment_uuid'] ?? 'Not available' }}
                        </td>

                        <td>
                            {{ $payment['service_name'] }}
                        </td>

                        <td>
                            {{ ucfirst($payment['method']) }}
                        </td>

                        <td>
                            {{ $payment['currency'] }}
                        </td>

                        <td class="right">
                            {{ number_format((float) $payment['amount'], 2) }}
                        </td>

                        <td>
                            {{ str_replace('_', ' ', ucfirst($payment['status'])) }}
                        </td>

                        <td>
                            {{ str_replace('_', ' ', ucfirst($payment['reconciliation_status'])) }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <p class="muted">
        Revenue is calculated from payment and refund source
        records. Clinical information is intentionally excluded.
    </p>
</body>
</html>
